import type { WorldDefinition } from "@pop/simulation/contracts";

export const world: WorldDefinition = {
  zone: {
    id: "zone:foundry",
    name: "Foundry District",
    description: "An old working district. A hundred people with plans. You are new here.",
  },
  npcCount: 99,
  firstNames: [
    "Mara",
    "Jonas",
    "Nadia",
    "Elias",
    "Lena",
    "Theo",
    "Alma",
    "Rafael",
    "Iris",
    "Omar",
    "Clara",
    "Leon",
    "Rosa",
    "Noah",
    "Sofia",
    "Hugo",
  ],
  lastNames: [
    "Costa",
    "Reed",
    "Vega",
    "Silva",
    "Ward",
    "Ramos",
    "Vale",
    "Park",
    "Moreau",
    "Santos",
    "Alves",
    "Marin",
    "Duarte",
    "Cross",
    "Rivera",
    "Stone",
  ],
  npcReputation: [30, 90],
  npcPopularity: [30, 90],
  npcInfluence: [1, 3],
  npcParticipationChance: 0.12,
  npcSupportChance: 0.68,
  initialProjects: [
    "streetlights",
    "night-market",
    "park-renovation",
    "public-assembly",
    "community-kitchen",
  ],
};
