import type { WorldContent } from "@pop/simulation/contracts";

export const world: WorldContent = {
  zone: {
    id: "zone:foundry",
    name: "Foundry District",
    description: "An old working district. People with plans. You are new here.",
  },
  firstNames: [
    "Mara",
    "Jonas",
    "Nadia",
    "Elias",
    "Lena",
    "Theo",
    "Alma",
    "Rafael",
    "Iris",
    "Omar",
    "Clara",
    "Leon",
    "Rosa",
    "Noah",
    "Sofia",
    "Hugo",
  ],
  lastNames: [
    "Costa",
    "Reed",
    "Vega",
    "Silva",
    "Ward",
    "Ramos",
    "Vale",
    "Park",
    "Moreau",
    "Santos",
    "Alves",
    "Marin",
    "Duarte",
    "Cross",
    "Rivera",
    "Stone",
  ],
};
